version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag_app
    environment:
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=${MYSQL_PORT_3306_TCP_ADDR}
      - SYMFONY__ENV__DATABASE_PORT=${MYSQL_PORT_3306_TCP_PORT}
      - SYMFONY__ENV__DATABASE_NAME=${MYSQL_DATABASE}
      - SYMFONY__ENV__DATABASE_USER=${MYSQL_USER}
      - SYMFONY__ENV__DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DOMAIN_NAME=${APP_URL}
      - SYMFONY__ENV__SERVER_NAME="[nuz:y]"
      - SYMFONY__ENV__FOSUSER_CONFIRMATION=false
      - SYMFONY__ENV__TWOFACTOR_AUTH=false
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8045:80"
    volumes:
      - ./images:/var/www/wallabag/web/assets/images
    depends_on:
      - db
      - redis
  db:
    image: mariadb
    container_name: wallabag_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql
  redis:
    image: redis:alpine
    container_name: wallabag_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s