version: '3'

services:
    db:
        image: postgres:15
        volumes:
            - ./joplindb:/var/lib/postgresql/data
        restart: unless-stopped
        env_file: .env
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "9016:22300"
        restart: unless-stopped
        env_file: .env