services:

  mealie:
    image: hkotel/mealie
    container_name: mealie-app
    hostname: mealie
    restart: always
    env_file: .env
    ports:
      - "9012:9000"
    # depends_on:
    #   - postgres
    volumes:
      - ./mealie_data/:/app/data
  # postgres:
  #   container_name: mealie-db
  #   image: postgres:15
    # restart: always
  #   volumes:
  #     - ./mealie_pgdata:/var/lib/postgresql/data
networks:
  default:
    name: $DOCKER_MY_NETWORK
    external: true